/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ceed.modeloexameneva2curso2021;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;

/**
 *
 * @author Paco Aldarias <paco.aldarias@ceedcv.es>
 */
public class Pregunta5 extends javax.swing.JFrame {

   // Configuración de la conexión a la base de datos
   private static final String DB_HOST = "localhost";
   private static final String DB_PORT = "3307"; //
   private static final String DB_NAME = "project";  //
   private static final String DB_URL = "jdbc:mysql://" + DB_HOST + ":" + DB_PORT + "/" + DB_NAME + "?serverTimezone=UTC";
   private static final String DB_USER = "project";
   private static final String DB_PASS = "*43i0;l+6=7:*lA";

   /**
    * Creates new form Pregunta4
    */
   public Pregunta5() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jButton1 = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      jButton2 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jButton1.setText("Mostrar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jTextArea1.setColumns(20);
      jTextArea1.setRows(5);
      jScrollPane1.setViewportView(jTextArea1);

      jButton2.setText("Importar");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(35, 35, 35)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(76, 76, 76)
                  .addComponent(jButton1)
                  .addGap(77, 77, 77)
                  .addComponent(jButton2)))
            .addContainerGap(51, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1)
               .addComponent(jButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(80, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:

      try {
         File f = new File("src/main/java/ficheros/personas.txt");

         Scanner sc = new Scanner(f);
         int c = 1;
         String texto = "";

         while (sc.hasNext()) {
            String linea = sc.nextLine();
            String elementos[] = linea.split(";");
            Persona p = new Persona();
            p.setId(Integer.parseInt(elementos[0]));
            p.setNombre(elementos[1]);
            texto += p.getId() + " " + p.getNombre() + "\n";
            jTextArea1.setText(texto);
            c++;

         }
         sc.close();
      } catch (FileNotFoundException ex) {
         ex.printStackTrace();
      }

   }//GEN-LAST:event_jButton1ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:

      try {
         File f = new File("src/main/java/ficheros/personas.txt");
         Scanner sc = new Scanner(f);

         Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
         Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
         int contador = 0;

         while (sc.hasNext()) {
            String linea = sc.nextLine();
            String elementos[] = linea.split(";");
            Persona p = new Persona();
            p.setId(Integer.parseInt(elementos[0]));
            p.setNombre(elementos[1]);

            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            String sql = "SELECT * FROM alumnos";
            ResultSet rs = stmt.executeQuery(sql);
            System.out.println("Insertando  " + linea);

            rs.moveToInsertRow();
            rs.updateString(1, p.getId() + "");
            rs.updateString(2, p.getNombre());
            rs.insertRow();
         }

         sc.close();

      } catch (Exception e) {
         e.printStackTrace();
      }

   }//GEN-LAST:event_jButton2ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;

            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Pregunta5.class
                 .getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Pregunta5.class
                 .getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Pregunta5.class
                 .getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Pregunta5.class
                 .getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Pregunta5().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration//GEN-END:variables
}
